version: 2

jobs:
  build: &build
    docker:
      - image: circleci/golang:1.9.4-stretch
    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run:
          name: Install packet cli and tools
          command: |
            docker create --name packet ebsarr/packet
            docker cp packet:/usr/local/bin/packet ./packet
            sudo mv ./packet /usr/local/bin/packet
            packet -v
            sudo apt-get update && sudo apt-get install -y --no-install-recommends jq unzip curl
            jq --version
            curl -o terraform.zip https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
            sudo unzip -d /usr/bin terraform.zip
            rm terraform.zip
            terraform --version

      - run:
          name: Provisioning a packer build machine
          command: |
            ./machine.sh create circle${CIRCLE_BUILD_NUM} ${HYPERVISOR}

      - run:
          name: Run packer build
          command: |
            ./build.sh circle${CIRCLE_BUILD_NUM} ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 5400

  upload: &upload
    docker:
      - image: microsoft/azure-cli:0.10.14
    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            apt-get update && apt-get install -y jq curl
            azure --version
            jq --version
            curl --version

      - run:
          name: Upload to Vagrant Cloud
          command: |
            ./upload.sh ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 3600

  upload: &upload
    docker:
      - image: microsoft/azure-cli:0.10.14
    steps:
      - checkout

      - run:
          name: Install tools
          command: |
            apt-get update && apt-get install -y jq curl
            azure --version
            jq --version
            curl --version

      - run:
          name: Upload to Vagrant Cloud
          command: |
            ./upload.sh ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 3600

  windows_2016_docker:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016_docker"
      - PACKET_PLAN: "baremetal_1"
      - PACKET_FACILITY: "ewr1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2016_docker_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016_docker"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_2016:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016"
      - PACKET_PLAN: "baremetal_1"
      - PACKET_FACILITY: "ewr1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2016_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_10:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - PACKET_PLAN: "baremetal_1"
      - PACKET_FACILITY: "ewr1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_10_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_2012_r2:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2012_r2"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "virtualbox+vmware"

  windows_2012_r2_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2012_r2"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_server_1709_docker:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_server_1709_docker"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "vmware"

  windows_2019_docker:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "vmware"
      - PACKET_FACILITY: "ewr1"

  windows_2019_docker_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2019_docker"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  windows_server_insider_docker:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_server_insider_docker"
      - PACKET_PLAN: "baremetal_1"
      - HYPERVISOR: "vmware"

  windows_server_insider_docker_hyperv:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_server_insider_docker"
      - AZURE_PLAN: "Standard_E4s_v3"
      - HYPERVISOR: "hyperv"

  upload_windows_2016_docker:
    <<: *upload
    environment:
      - PACKER_TEMPLATE: "windows_2016_docker"
      - HYPERVISOR: "virtualbox+vmware"

  upload_windows_2016:
    <<: *upload
    environment:
      - PACKER_TEMPLATE: "windows_2016"
      - HYPERVISOR: "virtualbox+vmware"

  upload_windows_10:
    <<: *upload
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "virtualbox+vmware"

workflows:
  version: 2
  build:
    jobs:
      # - windows_2019_docker_hyperv
      # - windows_2019_docker

      #- windows_2016_docker
      #- windows_2016_docker_hyperv
      - windows_2016
      #- windows_2016_hyperv
      #- windows_10
      #- windows_10_hyperv
      # - windows_2012_r2
      # - windows_2012_r2_hyperv

      # - approve_windows_2016_docker:
      #     type: approval
      #     requires:
      #       - windows_2016_docker
      # - upload_windows_2016_docker:
      #     requires:
      #       - approve_windows_2016_docker

      # - windows_2016
      # - approve_windows_2016:
      #     type: approval
      #     requires:
      #       - windows_2016
      # - upload_windows_2016:
      #     requires:
      #       - approve_windows_2016

      #- windows_10
      #- approve_windows_10:
      #    type: approval
      #    requires:
      #      - windows_10

      #- upload_windows_10
      #    requires:
      #    - approve_windows_10

      # - windows_server_1709_docker
      # - windows_server_insider_docker
      # - windows_server_insider_docker_hyperv
