version: 2

jobs:
  build:
    machine: true

    steps:
      - checkout

      - run:
          name: Install packet cli
          command: |
            go get -u github.com/ebsarr/packet
            packet -v
            jq --version
        
      - run:
          name: Provisioning a baremetal Packet.net server
          command: |
            ./packet.sh create circle$CIRCLE_BUILD_NUM

      - run:
          name: Run packer build windows_2016_docker
          command: |
            ./build.sh circle$CIRCLE_BUILD_NUM windows_2016_docker
          no_output_timeout: 3600

      - run:
          name: Delete baremetal Packet.net server
          command: |
            ./packet.sh delete circle$CIRCLE_BUILD_NUM
