version: 2

jobs:
  build: &build
    docker:
      - image: circleci/golang:1.9.4-stretch
    steps:
      - checkout
      
      - run:
          name: Install packet cli and tools
          command: |
            go get -u github.com/ebsarr/packet
            packet -v
            sudo apt-get update && sudo apt-get install -y jq
            jq --version
        
      - run:
          name: Provisioning a baremetal Packet.net server
          command: |
            ./packet.sh create circle${CIRCLE_BUILD_NUM}

      - run:
          name: Run packer build
          command: |
            ./build.sh circle${CIRCLE_BUILD_NUM} ${NAME}
          no_output_timeout: 3600

  windows_10:
    <<: *build
    environment:
      - NAME: "windows_10"

  windows_2016_docker:
    <<: *build
    environment:
      - NAME: "windows_2016_docker"

workflows:
  version: 2
  build:
    jobs:
      - windows_2016_docker
      - windows_10