version: 2

jobs:
  build: &build
    docker:
      - image: circleci/golang:1.9.4-stretch
    steps:
      - checkout
      
      - run:
          name: Install packet cli and tools
          command: |
            go get -u github.com/ebsarr/packet
            packet -v
            sudo apt-get update && sudo apt-get install -y jq
            jq --version
        
      - run:
          name: Provisioning a baremetal Packet.net server
          command: |
            ./packet.sh create circle${CIRCLE_BUILD_NUM} ${HYPERVISOR}

      - run:
          name: Run packer build
          command: |
            ./build.sh circle${CIRCLE_BUILD_NUM} ${PACKER_TEMPLATE} ${HYPERVISOR}
          no_output_timeout: 3600

  windows_2016_docker_virtualbox:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016_docker"
      - HYPERVISOR: "virtualbox"
      
  windows_2016_docker_vmware:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_2016_docker"
      - HYPERVISOR: "vmware"

  windows_10_virtualbox:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "virtualbox"

  windows_10_vmware:
    <<: *build
    environment:
      - PACKER_TEMPLATE: "windows_10"
      - HYPERVISOR: "vmware"

workflows:
  version: 2
  build:
    jobs:
      - windows_2016_docker_virtualbox
      - windows_2016_docker_vmware
#      - windows_10_virtualbox
#      - windows_10_vmware